-- Day Out tracker: schema, tables and row level security.
-- Run this in the Supabase SQL editor, then add "daysout" to
-- Project Settings > API > Exposed schemas so PostgREST can see it.

create schema if not exists daysout;

create table if not exists daysout.properties (
  id bigint generated by default as identity primary key,
  name text not null unique,
  location text,
  country text not null default 'England'
    check (country in ('England', 'Scotland', 'Wales', 'Northern Ireland')),
  institutions text[] not null default '{}',
  latitude double precision check (latitude between -90 and 90),
  longitude double precision check (longitude between -180 and 180),
  website text,
  notes text,
  created_at timestamptz not null default now()
);

-- A visit is a separate row rather than a flag on the property so a place can be
-- visited more than once, and so "visited but I can't remember when" stays valid
-- (visited_on is nullable).
create table if not exists daysout.visits (
  id bigint generated by default as identity primary key,
  property_id bigint not null references daysout.properties (id) on delete cascade,
  visited_on date,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists visits_property_id_idx on daysout.visits (property_id);
create index if not exists properties_institutions_idx on daysout.properties using gin (institutions);

grant usage on schema daysout to anon, authenticated;
grant all on all tables in schema daysout to anon, authenticated;
grant all on all sequences in schema daysout to anon, authenticated;

alter table daysout.properties enable row level security;
alter table daysout.visits enable row level security;

-- Signed-in users share one household list; the anon key alone cannot read or
-- write, so the published GitHub Pages build is not an open door to the data.
drop policy if exists "authenticated full access to properties" on daysout.properties;
create policy "authenticated full access to properties" on daysout.properties
for all to authenticated
using (true)
with check (true);

drop policy if exists "authenticated full access to visits" on daysout.visits;
create policy "authenticated full access to visits" on daysout.visits
for all to authenticated
using (true)
with check (true);

-- Starter list of UK properties and gardens (261 places).
-- Coordinates are approximate map positions, good to a few hundred metres, and
-- can be corrected in the app. Re-running this is safe: existing names are kept.

insert into daysout.properties (name, location, country, institutions, latitude, longitude)
values
  ('Chartwell', 'Kent', 'England', array['National Trust'], 51.244, 0.08),
  ('Sissinghurst Castle Garden', 'Kent', 'England', array['National Trust'], 51.117, 0.583),
  ('Bodiam Castle', 'East Sussex', 'England', array['National Trust'], 51.0025, 0.5433),
  ('Knole', 'Kent', 'England', array['National Trust'], 51.268, 0.2),
  ('Ightham Mote', 'Kent', 'England', array['National Trust'], 51.272, 0.287),
  ('Scotney Castle', 'Kent', 'England', array['National Trust'], 51.087, 0.409),
  ('Petworth House and Park', 'West Sussex', 'England', array['National Trust'], 50.987, -0.612),
  ('Uppark House and Garden', 'West Sussex', 'England', array['National Trust'], 50.941, -0.89),
  ('Nymans', 'West Sussex', 'England', array['National Trust'], 51.045, -0.173),
  ('Sheffield Park and Garden', 'East Sussex', 'England', array['National Trust'], 50.993, -0.009),
  ('Standen House and Garden', 'West Sussex', 'England', array['National Trust'], 51.112, -0.025),
  ('Polesden Lacey', 'Surrey', 'England', array['National Trust'], 51.262, -0.38),
  ('Clandon Park', 'Surrey', 'England', array['National Trust'], 51.245, -0.525),
  ('Hatchlands Park', 'Surrey', 'England', array['National Trust'], 51.25, -0.462),
  ('Claremont Landscape Garden', 'Surrey', 'England', array['National Trust'], 51.356, -0.369),
  ('Osterley Park and House', 'London', 'England', array['National Trust'], 51.482, -0.345),
  ('Ham House and Garden', 'London', 'England', array['National Trust'], 51.445, -0.313),
  ('Cliveden', 'Buckinghamshire', 'England', array['National Trust'], 51.558, -0.689),
  ('Hughenden', 'Buckinghamshire', 'England', array['National Trust'], 51.647, -0.762),
  ('Waddesdon Manor', 'Buckinghamshire', 'England', array['National Trust'], 51.842, -0.937),
  ('Stowe', 'Buckinghamshire', 'England', array['National Trust'], 52.029, -1.014),
  ('Ascott', 'Buckinghamshire', 'England', array['National Trust'], 51.879, -0.681),
  ('Basildon Park', 'Berkshire', 'England', array['National Trust'], 51.49, -1.121),
  ('The Vyne', 'Hampshire', 'England', array['National Trust'], 51.29, -1.067),
  ('Mottisfont', 'Hampshire', 'England', array['National Trust'], 51.033, -1.535),
  ('Hinton Ampner', 'Hampshire', 'England', array['National Trust'], 51.033, -1.16),
  ('Stourhead', 'Wiltshire', 'England', array['National Trust'], 51.103, -2.322),
  ('Lacock Abbey, Village and Museum', 'Wiltshire', 'England', array['National Trust'], 51.415, -2.122),
  ('Avebury', 'Wiltshire', 'England', array['National Trust'], 51.4286, -1.8542),
  ('Great Chalfield Manor and Garden', 'Wiltshire', 'England', array['National Trust'], 51.356, -2.211),
  ('Kingston Lacy', 'Dorset', 'England', array['National Trust'], 50.814, -2.027),
  ('Corfe Castle', 'Dorset', 'England', array['National Trust'], 50.64, -2.057),
  ('Brownsea Island', 'Dorset', 'England', array['National Trust'], 50.693, -1.975),
  ('Dyrham Park', 'Gloucestershire', 'England', array['National Trust'], 51.483, -2.376),
  ('Hidcote', 'Gloucestershire', 'England', array['National Trust'], 52.081, -1.76),
  ('Snowshill Manor and Garden', 'Gloucestershire', 'England', array['National Trust'], 52.025, -1.834),
  ('Chedworth Roman Villa', 'Gloucestershire', 'England', array['National Trust'], 51.825, -1.92),
  ('Westbury Court Garden', 'Gloucestershire', 'England', array['National Trust'], 51.845, -2.403),
  ('Tyntesfield', 'Somerset', 'England', array['National Trust'], 51.436, -2.71),
  ('Montacute House', 'Somerset', 'England', array['National Trust'], 50.952, -2.715),
  ('Barrington Court', 'Somerset', 'England', array['National Trust'], 50.97, -2.888),
  ('Dunster Castle and Watermill', 'Somerset', 'England', array['National Trust'], 51.183, -3.444),
  ('Lytes Cary Manor', 'Somerset', 'England', array['National Trust'], 51.03, -2.67),
  ('Killerton', 'Devon', 'England', array['National Trust'], 50.79, -3.452),
  ('Saltram', 'Devon', 'England', array['National Trust'], 50.39, -4.08),
  ('Castle Drogo', 'Devon', 'England', array['National Trust'], 50.698, -3.809),
  ('Knightshayes', 'Devon', 'England', array['National Trust'], 50.921, -3.47),
  ('Arlington Court', 'Devon', 'England', array['National Trust'], 51.133, -3.982),
  ('Lanhydrock', 'Cornwall', 'England', array['National Trust'], 50.438, -4.697),
  ('Trelissick', 'Cornwall', 'England', array['National Trust'], 50.217, -5.033),
  ('Trerice', 'Cornwall', 'England', array['National Trust'], 50.38, -5.03),
  ('Cotehele', 'Cornwall', 'England', array['National Trust'], 50.492, -4.223),
  ('Glendurgan Garden', 'Cornwall', 'England', array['National Trust'], 50.105, -5.112),
  ('Trengwainton Garden', 'Cornwall', 'England', array['National Trust'], 50.129, -5.57),
  ('St Michael''s Mount', 'Cornwall', 'England', array['National Trust'], 50.117, -5.478),
  ('Blickling Estate', 'Norfolk', 'England', array['National Trust'], 52.813, 1.18),
  ('Felbrigg Hall, Gardens and Estate', 'Norfolk', 'England', array['National Trust'], 52.907, 1.25),
  ('Oxburgh Estate', 'Norfolk', 'England', array['National Trust'], 52.585, 0.568),
  ('Sheringham Park', 'Norfolk', 'England', array['National Trust'], 52.925, 1.19),
  ('Ickworth', 'Suffolk', 'England', array['National Trust'], 52.228, 0.666),
  ('Melford Hall', 'Suffolk', 'England', array['National Trust'], 52.077, 0.718),
  ('Anglesey Abbey, Gardens and Lode Mill', 'Cambridgeshire', 'England', array['National Trust'], 52.235, 0.247),
  ('Wimpole Estate', 'Cambridgeshire', 'England', array['National Trust'], 52.14, -0.043),
  ('Peckover House and Garden', 'Cambridgeshire', 'England', array['National Trust'], 52.668, 0.159),
  ('Wicken Fen National Nature Reserve', 'Cambridgeshire', 'England', array['National Trust'], 52.314, 0.29),
  ('Hatfield Forest', 'Essex', 'England', array['National Trust'], 51.86, 0.24),
  ('Charlecote Park', 'Warwickshire', 'England', array['National Trust'], 52.183, -1.622),
  ('Baddesley Clinton', 'Warwickshire', 'England', array['National Trust'], 52.352, -1.702),
  ('Packwood House', 'Warwickshire', 'England', array['National Trust'], 52.362, -1.755),
  ('Coughton Court', 'Warwickshire', 'England', array['National Trust'], 52.244, -1.872),
  ('Upton House and Gardens', 'Warwickshire', 'England', array['National Trust'], 52.091, -1.447),
  ('Croome', 'Worcestershire', 'England', array['National Trust'], 52.102, -2.17),
  ('Hanbury Hall and Gardens', 'Worcestershire', 'England', array['National Trust'], 52.268, -2.123),
  ('Berrington Hall', 'Herefordshire', 'England', array['National Trust'], 52.247, -2.718),
  ('Croft Castle and Parkland', 'Herefordshire', 'England', array['National Trust'], 52.276, -2.81),
  ('Attingham Park', 'Shropshire', 'England', array['National Trust'], 52.69, -2.67),
  ('Dudmaston', 'Shropshire', 'England', array['National Trust'], 52.509, -2.383),
  ('Shugborough Estate', 'Staffordshire', 'England', array['National Trust'], 52.794, -2),
  ('Biddulph Grange Garden', 'Staffordshire', 'England', array['National Trust'], 53.122, -2.165),
  ('Ilam Park', 'Staffordshire', 'England', array['National Trust'], 53.053, -1.806),
  ('Calke Abbey', 'Derbyshire', 'England', array['National Trust'], 52.806, -1.457),
  ('Kedleston Hall', 'Derbyshire', 'England', array['National Trust'], 52.966, -1.54),
  ('Hardwick Hall', 'Derbyshire', 'England', array['National Trust'], 53.169, -1.309),
  ('Lyme', 'Cheshire', 'England', array['National Trust'], 53.339, -2.05),
  ('Dunham Massey', 'Greater Manchester', 'England', array['National Trust'], 53.383, -2.39),
  ('Quarry Bank', 'Cheshire', 'England', array['National Trust'], 53.34, -2.247),
  ('Little Moreton Hall', 'Cheshire', 'England', array['National Trust'], 53.144, -2.262),
  ('Speke Hall', 'Merseyside', 'England', array['National Trust'], 53.332, -2.872),
  ('Rufford Old Hall', 'Lancashire', 'England', array['National Trust'], 53.635, -2.808),
  ('Gawthorpe Hall', 'Lancashire', 'England', array['National Trust'], 53.797, -2.232),
  ('Sizergh', 'Cumbria', 'England', array['National Trust'], 54.286, -2.783),
  ('Hill Top', 'Cumbria', 'England', array['National Trust'], 54.35, -2.972),
  ('Wray Castle', 'Cumbria', 'England', array['National Trust'], 54.39, -2.964),
  ('Acorn Bank', 'Cumbria', 'England', array['National Trust'], 54.642, -2.59),
  ('Beningbrough', 'North Yorkshire', 'England', array['National Trust'], 54.03, -1.172),
  ('Fountains Abbey and Studley Royal', 'North Yorkshire', 'England', array['National Trust'], 54.111, -1.581),
  ('Nostell', 'West Yorkshire', 'England', array['National Trust'], 53.656, -1.38),
  ('Nunnington Hall', 'North Yorkshire', 'England', array['National Trust'], 54.19, -0.97),
  ('Ormesby Hall', 'North Yorkshire', 'England', array['National Trust'], 54.545, -1.183),
  ('East Riddlesden Hall', 'West Yorkshire', 'England', array['National Trust'], 53.87, -1.888),
  ('Cragside', 'Northumberland', 'England', array['National Trust'], 55.31, -1.88),
  ('Wallington', 'Northumberland', 'England', array['National Trust'], 55.129, -1.955),
  ('Lindisfarne Castle', 'Northumberland', 'England', array['National Trust'], 55.669, -1.785),
  ('Seaton Delaval Hall', 'Northumberland', 'England', array['National Trust'], 55.077, -1.52),
  ('Gibside', 'Tyne and Wear', 'England', array['National Trust'], 54.928, -1.73),
  ('Washington Old Hall', 'Tyne and Wear', 'England', array['National Trust'], 54.907, -1.52),
  ('Chirk Castle', 'Wrexham', 'Wales', array['National Trust'], 52.933, -3.089),
  ('Erddig', 'Wrexham', 'Wales', array['National Trust'], 53.018, -3.014),
  ('Powis Castle and Garden', 'Powys', 'Wales', array['National Trust'], 52.656, -3.16),
  ('Bodnant Garden', 'Conwy', 'Wales', array['National Trust'], 53.234, -3.798),
  ('Penrhyn Castle and Garden', 'Gwynedd', 'Wales', array['National Trust'], 53.227, -4.093),
  ('Plas Newydd House and Garden', 'Anglesey', 'Wales', array['National Trust'], 53.2, -4.19),
  ('Tredegar House', 'Newport', 'Wales', array['National Trust'], 51.568, -3.027),
  ('Dinefwr', 'Carmarthenshire', 'Wales', array['National Trust'], 51.88, -4),
  ('Dyffryn Gardens', 'Vale of Glamorgan', 'Wales', array['National Trust'], 51.446, -3.29),
  ('Mount Stewart', 'County Down', 'Northern Ireland', array['National Trust'], 54.551, -5.603),
  ('Castle Ward', 'County Down', 'Northern Ireland', array['National Trust'], 54.37, -5.58),
  ('Rowallane Garden', 'County Down', 'Northern Ireland', array['National Trust'], 54.418, -5.79),
  ('The Argory', 'County Armagh', 'Northern Ireland', array['National Trust'], 54.47, -6.64),
  ('Florence Court', 'County Fermanagh', 'Northern Ireland', array['National Trust'], 54.256, -7.722),
  ('Castle Coole', 'County Fermanagh', 'Northern Ireland', array['National Trust'], 54.34, -7.61),
  ('Giant''s Causeway', 'County Antrim', 'Northern Ireland', array['National Trust'], 55.2408, -6.5116),
  ('Carrick-a-Rede', 'County Antrim', 'Northern Ireland', array['National Trust'], 55.239, -6.33),
  ('Stonehenge', 'Wiltshire', 'England', array['English Heritage'], 51.1789, -1.8262),
  ('Old Sarum', 'Wiltshire', 'England', array['English Heritage'], 51.093, -1.805),
  ('Dover Castle', 'Kent', 'England', array['English Heritage'], 51.1295, 1.321),
  ('Walmer Castle and Gardens', 'Kent', 'England', array['English Heritage'], 51.202, 1.402),
  ('Rochester Castle', 'Kent', 'England', array['English Heritage'], 51.389, 0.503),
  ('Down House', 'Kent', 'England', array['English Heritage'], 51.331, 0.053),
  ('Battle Abbey', 'East Sussex', 'England', array['English Heritage'], 50.914, 0.487),
  ('Pevensey Castle', 'East Sussex', 'England', array['English Heritage'], 50.819, 0.334),
  ('Eltham Palace and Gardens', 'London', 'England', array['English Heritage'], 51.449, 0.053),
  ('Osborne', 'Isle of Wight', 'England', array['English Heritage'], 50.751, -1.265),
  ('Carisbrooke Castle', 'Isle of Wight', 'England', array['English Heritage'], 50.687, -1.314),
  ('Portchester Castle', 'Hampshire', 'England', array['English Heritage'], 50.837, -1.113),
  ('Tintagel Castle', 'Cornwall', 'England', array['English Heritage'], 50.668, -4.76),
  ('Audley End House and Gardens', 'Essex', 'England', array['English Heritage'], 52.022, 0.213),
  ('Wrest Park', 'Bedfordshire', 'England', array['English Heritage'], 51.98, -0.413),
  ('Framlingham Castle', 'Suffolk', 'England', array['English Heritage'], 52.223, 1.345),
  ('Orford Castle', 'Suffolk', 'England', array['English Heritage'], 52.094, 1.534),
  ('Castle Acre Priory', 'Norfolk', 'England', array['English Heritage'], 52.705, 0.683),
  ('Kirby Hall', 'Northamptonshire', 'England', array['English Heritage'], 52.493, -0.63),
  ('Ashby de la Zouch Castle', 'Leicestershire', 'England', array['English Heritage'], 52.745, -1.474),
  ('Kenilworth Castle and Elizabethan Garden', 'Warwickshire', 'England', array['English Heritage'], 52.348, -1.595),
  ('Witley Court and Gardens', 'Worcestershire', 'England', array['English Heritage'], 52.287, -2.33),
  ('Goodrich Castle', 'Herefordshire', 'England', array['English Heritage'], 51.876, -2.618),
  ('Stokesay Castle', 'Shropshire', 'England', array['English Heritage'], 52.429, -2.83),
  ('Wroxeter Roman City', 'Shropshire', 'England', array['English Heritage'], 52.673, -2.647),
  ('Bolsover Castle', 'Derbyshire', 'England', array['English Heritage'], 53.229, -1.293),
  ('Brodsworth Hall and Gardens', 'South Yorkshire', 'England', array['English Heritage'], 53.562, -1.22),
  ('Clifford''s Tower', 'York', 'England', array['English Heritage'], 53.956, -1.08),
  ('Whitby Abbey', 'North Yorkshire', 'England', array['English Heritage'], 54.488, -0.607),
  ('Rievaulx Abbey', 'North Yorkshire', 'England', array['English Heritage'], 54.257, -1.117),
  ('Scarborough Castle', 'North Yorkshire', 'England', array['English Heritage'], 54.287, -0.386),
  ('Richmond Castle', 'North Yorkshire', 'England', array['English Heritage'], 54.402, -1.737),
  ('Furness Abbey', 'Cumbria', 'England', array['English Heritage'], 54.129, -3.217),
  ('Carlisle Castle', 'Cumbria', 'England', array['English Heritage'], 54.897, -2.941),
  ('Housesteads Roman Fort', 'Northumberland', 'England', array['English Heritage'], 55.012, -2.331),
  ('Chesters Roman Fort and Museum', 'Northumberland', 'England', array['English Heritage'], 55.027, -2.138),
  ('Lindisfarne Priory', 'Northumberland', 'England', array['English Heritage'], 55.669, -1.802),
  ('Dunstanburgh Castle', 'Northumberland', 'England', array['English Heritage'], 55.489, -1.594),
  ('Warkworth Castle', 'Northumberland', 'England', array['English Heritage'], 55.346, -1.612),
  ('Belsay Hall, Castle and Gardens', 'Northumberland', 'England', array['English Heritage'], 55.093, -1.86),
  ('Tynemouth Priory and Castle', 'Tyne and Wear', 'England', array['English Heritage'], 55.018, -1.419),
  ('Culzean Castle and Country Park', 'South Ayrshire', 'Scotland', array['National Trust for Scotland'], 55.355, -4.79),
  ('Robert Burns Birthplace Museum', 'South Ayrshire', 'Scotland', array['National Trust for Scotland'], 55.43, -4.64),
  ('Brodick Castle and Garden', 'Isle of Arran', 'Scotland', array['National Trust for Scotland'], 55.6, -5.15),
  ('Pollok House', 'Glasgow', 'Scotland', array['National Trust for Scotland'], 55.828, -4.308),
  ('The Hill House', 'Argyll and Bute', 'Scotland', array['National Trust for Scotland'], 56.004, -4.746),
  ('Arduaine Garden', 'Argyll and Bute', 'Scotland', array['National Trust for Scotland'], 56.22, -5.56),
  ('Glencoe National Nature Reserve', 'Highland', 'Scotland', array['National Trust for Scotland'], 56.67, -5.1),
  ('Glenfinnan Monument', 'Highland', 'Scotland', array['National Trust for Scotland'], 56.872, -5.436),
  ('Inverewe Garden', 'Highland', 'Scotland', array['National Trust for Scotland'], 57.775, -5.598),
  ('Brodie Castle', 'Moray', 'Scotland', array['National Trust for Scotland'], 57.6, -3.71),
  ('Crathes Castle and Garden', 'Aberdeenshire', 'Scotland', array['National Trust for Scotland'], 57.062, -2.437),
  ('Drum Castle and Garden', 'Aberdeenshire', 'Scotland', array['National Trust for Scotland'], 57.093, -2.313),
  ('Craigievar Castle', 'Aberdeenshire', 'Scotland', array['National Trust for Scotland'], 57.09, -2.71),
  ('Fyvie Castle', 'Aberdeenshire', 'Scotland', array['National Trust for Scotland'], 57.44, -2.39),
  ('Haddo House', 'Aberdeenshire', 'Scotland', array['National Trust for Scotland'], 57.37, -2.22),
  ('Falkland Palace and Garden', 'Fife', 'Scotland', array['National Trust for Scotland'], 56.253, -3.204),
  ('Culross Palace', 'Fife', 'Scotland', array['National Trust for Scotland'], 56.056, -3.63),
  ('Kellie Castle and Garden', 'Fife', 'Scotland', array['National Trust for Scotland'], 56.24, -2.78),
  ('Hill of Tarvit', 'Fife', 'Scotland', array['National Trust for Scotland'], 56.286, -3.017),
  ('Branklyn Garden', 'Perth and Kinross', 'Scotland', array['National Trust for Scotland'], 56.391, -3.416),
  ('Bannockburn', 'Stirling', 'Scotland', array['National Trust for Scotland'], 56.09, -3.92),
  ('Newhailes', 'East Lothian', 'Scotland', array['National Trust for Scotland'], 55.94, -3.07),
  ('Threave Garden and Estate', 'Dumfries and Galloway', 'Scotland', array['National Trust for Scotland'], 54.928, -3.9),
  ('Edinburgh Castle', 'Edinburgh', 'Scotland', array['Historic Environment Scotland'], 55.9486, -3.1999),
  ('Craigmillar Castle', 'Edinburgh', 'Scotland', array['Historic Environment Scotland'], 55.928, -3.14),
  ('Linlithgow Palace', 'West Lothian', 'Scotland', array['Historic Environment Scotland'], 55.978, -3.601),
  ('Blackness Castle', 'Falkirk', 'Scotland', array['Historic Environment Scotland'], 56.006, -3.515),
  ('Stirling Castle', 'Stirling', 'Scotland', array['Historic Environment Scotland'], 56.1236, -3.9472),
  ('Doune Castle', 'Stirling', 'Scotland', array['Historic Environment Scotland'], 56.186, -4.051),
  ('Dunfermline Abbey and Palace', 'Fife', 'Scotland', array['Historic Environment Scotland'], 56.07, -3.463),
  ('St Andrews Cathedral', 'Fife', 'Scotland', array['Historic Environment Scotland'], 56.339, -2.788),
  ('Melrose Abbey', 'Scottish Borders', 'Scotland', array['Historic Environment Scotland'], 55.599, -2.718),
  ('Dryburgh Abbey', 'Scottish Borders', 'Scotland', array['Historic Environment Scotland'], 55.576, -2.654),
  ('Jedburgh Abbey', 'Scottish Borders', 'Scotland', array['Historic Environment Scotland'], 55.478, -2.554),
  ('Caerlaverock Castle', 'Dumfries and Galloway', 'Scotland', array['Historic Environment Scotland'], 55.006, -3.524),
  ('Urquhart Castle', 'Highland', 'Scotland', array['Historic Environment Scotland'], 57.324, -4.442),
  ('Fort George', 'Highland', 'Scotland', array['Historic Environment Scotland'], 57.583, -4.072),
  ('Elgin Cathedral', 'Moray', 'Scotland', array['Historic Environment Scotland'], 57.651, -3.311),
  ('Dunstaffnage Castle', 'Argyll and Bute', 'Scotland', array['Historic Environment Scotland'], 56.454, -5.438),
  ('Iona Abbey', 'Argyll and Bute', 'Scotland', array['Historic Environment Scotland'], 56.335, -6.39),
  ('Skara Brae', 'Orkney', 'Scotland', array['Historic Environment Scotland'], 59.049, -3.342),
  ('Ring of Brodgar', 'Orkney', 'Scotland', array['Historic Environment Scotland'], 59.001, -3.229),
  ('Jarlshof', 'Shetland', 'Scotland', array['Historic Environment Scotland'], 59.872, -1.294),
  ('Caernarfon Castle', 'Gwynedd', 'Wales', array['Cadw'], 53.1395, -4.277),
  ('Conwy Castle', 'Conwy', 'Wales', array['Cadw'], 53.28, -3.825),
  ('Harlech Castle', 'Gwynedd', 'Wales', array['Cadw'], 52.86, -4.109),
  ('Beaumaris Castle', 'Anglesey', 'Wales', array['Cadw'], 53.265, -4.09),
  ('Criccieth Castle', 'Gwynedd', 'Wales', array['Cadw'], 52.918, -4.232),
  ('Caerphilly Castle', 'Caerphilly', 'Wales', array['Cadw'], 51.576, -3.22),
  ('Castell Coch', 'Cardiff', 'Wales', array['Cadw'], 51.536, -3.254),
  ('Chepstow Castle', 'Monmouthshire', 'Wales', array['Cadw'], 51.645, -2.675),
  ('Raglan Castle', 'Monmouthshire', 'Wales', array['Cadw'], 51.765, -2.852),
  ('Tintern Abbey', 'Monmouthshire', 'Wales', array['Cadw'], 51.697, -2.677),
  ('Valle Crucis Abbey', 'Denbighshire', 'Wales', array['Cadw'], 52.986, -3.183),
  ('St Davids Bishop''s Palace', 'Pembrokeshire', 'Wales', array['Cadw'], 51.882, -5.269),
  ('RHS Garden Wisley', 'Surrey', 'England', array['RHS Garden'], 51.311, -0.474),
  ('RHS Garden Rosemoor', 'Devon', 'England', array['RHS Garden'], 50.952, -4.15),
  ('RHS Garden Harlow Carr', 'North Yorkshire', 'England', array['RHS Garden'], 53.993, -1.562),
  ('RHS Garden Hyde Hall', 'Essex', 'England', array['RHS Garden'], 51.639, 0.556),
  ('RHS Garden Bridgewater', 'Greater Manchester', 'England', array['RHS Garden'], 53.501, -2.403),
  ('Chatsworth House', 'Derbyshire', 'England', array['Historic Houses'], 53.228, -1.611),
  ('Blenheim Palace', 'Oxfordshire', 'England', array['Historic Houses'], 51.8417, -1.361),
  ('Highclere Castle', 'Hampshire', 'England', array['Historic Houses'], 51.327, -1.36),
  ('Longleat', 'Wiltshire', 'England', array['Historic Houses'], 51.185, -2.27),
  ('Bowood House and Gardens', 'Wiltshire', 'England', array['Historic Houses'], 51.43, -2.04),
  ('Wilton House', 'Wiltshire', 'England', array['Historic Houses'], 51.08, -1.86),
  ('Castle Howard', 'North Yorkshire', 'England', array['Historic Houses'], 54.121, -0.907),
  ('Harewood House', 'West Yorkshire', 'England', array['Historic Houses'], 53.894, -1.529),
  ('Newby Hall and Gardens', 'North Yorkshire', 'England', array['Historic Houses', 'RHS Partner Garden'], 54.09, -1.44),
  ('Burghley House', 'Lincolnshire', 'England', array['Historic Houses'], 52.643, -0.45),
  ('Alnwick Castle', 'Northumberland', 'England', array['Historic Houses'], 55.416, -1.706),
  ('The Alnwick Garden', 'Northumberland', 'England', array['RHS Partner Garden'], 55.415, -1.71),
  ('Hever Castle and Gardens', 'Kent', 'England', array['Historic Houses'], 51.186, 0.115),
  ('Leeds Castle', 'Kent', 'England', array['Historic Houses'], 51.249, 0.63),
  ('Great Dixter House and Gardens', 'East Sussex', 'England', array['RHS Partner Garden'], 51.004, 0.63),
  ('Borde Hill Garden', 'West Sussex', 'England', array['RHS Partner Garden'], 51.029, -0.118),
  ('Arundel Castle', 'West Sussex', 'England', array['Historic Houses'], 50.856, -0.554),
  ('Goodwood House', 'West Sussex', 'England', array['Historic Houses'], 50.88, -0.74),
  ('Beaulieu', 'Hampshire', 'England', array['Historic Houses'], 50.818, -1.452),
  ('Woburn Abbey', 'Bedfordshire', 'England', array['Historic Houses'], 51.987, -0.606),
  ('Syon House', 'London', 'England', array['Historic Houses'], 51.482, -0.308),
  ('Royal Botanic Gardens, Kew', 'London', 'England', array['RHS Partner Garden'], 51.4787, -0.2956),
  ('Holkham Hall', 'Norfolk', 'England', array['Historic Houses'], 52.949, 0.806),
  ('Houghton Hall', 'Norfolk', 'England', array['Historic Houses'], 52.825, 0.657),
  ('Bressingham Gardens', 'Norfolk', 'England', array['RHS Partner Garden'], 52.38, 1),
  ('Levens Hall and Gardens', 'Cumbria', 'England', array['Historic Houses', 'RHS Partner Garden'], 54.26, -2.777),
  ('Holker Hall and Gardens', 'Cumbria', 'England', array['Historic Houses'], 54.203, -2.966),
  ('Trebah Garden', 'Cornwall', 'England', array['RHS Partner Garden'], 50.103, -5.12),
  ('The Lost Gardens of Heligan', 'Cornwall', 'England', array['RHS Partner Garden'], 50.28, -4.817),
  ('The Eden Project', 'Cornwall', 'England', array[]::text[], 50.3619, -4.7447),
  ('Abbotsbury Subtropical Gardens', 'Dorset', 'England', array['RHS Partner Garden'], 50.664, -2.61),
  ('Marwood Hill Gardens', 'Devon', 'England', array['RHS Partner Garden'], 51.112, -4.07),
  ('Hopetoun House', 'West Lothian', 'Scotland', array['Historic Houses'], 55.991, -3.44),
  ('Scone Palace', 'Perth and Kinross', 'Scotland', array['Historic Houses'], 56.418, -3.437),
  ('Glamis Castle', 'Angus', 'Scotland', array['Historic Houses'], 56.621, -3),
  ('Blair Castle', 'Perth and Kinross', 'Scotland', array['Historic Houses'], 56.77, -3.85),
  ('Inveraray Castle', 'Argyll and Bute', 'Scotland', array['Historic Houses'], 56.238, -5.074)
on conflict (name) do nothing;

-- More Historic Houses and RHS Partner Garden properties (52 places),
-- filling out two categories that were thin in the original seed. Gathered
-- from web search result snippets against historichouses.org and rhs.org.uk
-- (both block direct fetches), cross-checked against each other; coordinates
-- are approximate map positions, same as the original seed. Re-running this
-- is safe: existing names are kept, and the two institution updates below are
-- idempotent.

insert into daysout.properties (name, location, country, institutions, latitude, longitude)
values
  ('Althorp', 'Northamptonshire', 'England', array['Historic Houses'], 52.303, -0.973),
  ('Knebworth House', 'Hertfordshire', 'England', array['Historic Houses'], 51.8508, -0.1953),
  ('Wentworth Woodhouse', 'South Yorkshire', 'England', array['Historic Houses'], 53.4936, -1.3583),
  ('Bolton Castle', 'North Yorkshire', 'England', array['Historic Houses'], 54.3011, -1.9236),
  ('Brockfield Hall', 'North Yorkshire', 'England', array['Historic Houses'], 53.9647, -1.0122),
  ('Parcevall Hall Gardens', 'North Yorkshire', 'England', array['Historic Houses'], 54.0665, -1.9187),
  ('Grimsthorpe Castle, Park and Gardens', 'Lincolnshire', 'England', array['Historic Houses'], 52.7908, -0.4165),
  ('Sudeley Castle and Gardens', 'Gloucestershire', 'England', array['Historic Houses'], 51.9518, -1.9534),
  ('Stanway House', 'Gloucestershire', 'England', array['Historic Houses'], 51.9741, -1.9017),
  ('Sezincote House', 'Gloucestershire', 'England', array['Historic Houses'], 51.9967, -1.7394),
  ('Kelmscott Manor', 'Oxfordshire', 'England', array['Historic Houses'], 51.6853, -1.6444),
  ('Rodmarton Manor', 'Gloucestershire', 'England', array['Historic Houses'], 51.7154, -2.0503),
  ('Corsham Court', 'Wiltshire', 'England', array['Historic Houses'], 51.4258, -2.1897),
  ('Eastnor Castle', 'Herefordshire', 'England', array['Historic Houses'], 52.0333, -2.4177),
  ('Little Malvern Court', 'Worcestershire', 'England', array['Historic Houses'], 52.0642, -2.3298),
  ('Walcot Hall', 'Shropshire', 'England', array['Historic Houses'], 52.4344, -2.8377),
  ('Lullingstone Castle', 'Kent', 'England', array['Historic Houses'], 51.3746, 0.1961),
  ('Chawton House', 'Hampshire', 'England', array['Historic Houses'], 51.1444, -0.9776),
  ('Loseley Park', 'Surrey', 'England', array['Historic Houses'], 51.2129, -0.6206),
  ('Wolterton Hall', 'Norfolk', 'England', array['Historic Houses'], 52.8636, 1.2394),
  ('Somerleyton Hall and Gardens', 'Suffolk', 'England', array['Historic Houses'], 52.4894, 1.6469),
  ('Floors Castle', 'Scottish Borders', 'Scotland', array['Historic Houses'], 55.6017, -2.446),
  ('Thirlestane Castle', 'Scottish Borders', 'Scotland', array['Historic Houses'], 55.6083, -2.6773),
  ('Traquair House', 'Scottish Borders', 'Scotland', array['Historic Houses'], 55.5716, -3.018),
  ('Dunrobin Castle', 'Highland', 'Scotland', array['Historic Houses'], 57.9698, -3.9469),
  ('York Gate Garden', 'West Yorkshire', 'England', array['RHS Partner Garden'], 53.8647, -1.5936),
  ('Sefton Park Palm House', 'Merseyside', 'England', array['RHS Partner Garden'], 53.3778, -2.9251),
  ('East Lambrook Manor Garden', 'Somerset', 'England', array['RHS Partner Garden'], 50.9613, -2.7936),
  ('The Newt in Somerset', 'Somerset', 'England', array['RHS Partner Garden'], 51.087, -2.599),
  ('Hestercombe House and Gardens', 'Somerset', 'England', array['RHS Partner Garden'], 51.0219, -3.1414),
  ('The Bishop''s Palace Gardens', 'Somerset', 'England', array['RHS Partner Garden'], 51.2088, -2.6444),
  ('Kilver Court Gardens', 'Somerset', 'England', array['RHS Partner Garden'], 51.1929, -2.5453),
  ('Keyneston Mill', 'Dorset', 'England', array['RHS Partner Garden'], 50.8917, -2.1614),
  ('Forde Abbey and Gardens', 'Dorset', 'England', array['RHS Partner Garden'], 50.8347, -2.7936),
  ('Minterne Gardens', 'Dorset', 'England', array['RHS Partner Garden'], 50.8206, -2.4802),
  ('Athelhampton House and Gardens', 'Dorset', 'England', array['RHS Partner Garden'], 50.7361, -2.3628),
  ('Compton Acres', 'Dorset', 'England', array['RHS Partner Garden'], 50.708, -1.9494),
  ('Dartington Hall Gardens', 'Devon', 'England', array['RHS Partner Garden'], 50.4406, -3.6997),
  ('Coleton Fishacre', 'Devon', 'England', array['RHS Partner Garden'], 50.3311, -3.5636),
  ('Castle Hill Gardens', 'Devon', 'England', array['RHS Partner Garden'], 51.0126, -3.8347),
  ('Hotel Endsleigh Gardens', 'Devon', 'England', array['RHS Partner Garden'], 50.5661, -4.2436),
  ('Wyken Hall Gardens', 'Suffolk', 'England', array['RHS Partner Garden'], 52.2494, 0.8264),
  ('Castle Bromwich Hall Gardens', 'West Midlands', 'England', array['RHS Partner Garden'], 52.5083, -1.7728),
  ('Cascades Gardens', 'Derbyshire', 'England', array['RHS Partner Garden'], 53.085, -1.4544),
  ('Bluebell Arboretum and Nursery', 'Derbyshire', 'England', array['RHS Partner Garden'], 52.7539, -1.4694),
  ('Himalayan Garden and Sculpture Park', 'North Yorkshire', 'England', array['RHS Partner Garden'], 54.2419, -1.5661),
  ('Teasses Gardens', 'Fife', 'Scotland', array['RHS Partner Garden'], 56.2775, -2.8734),
  ('Castle Kennedy Gardens', 'Dumfries and Galloway', 'Scotland', array['RHS Partner Garden'], 54.9014, -4.9425),
  ('Abbotsford House Gardens', 'Scottish Borders', 'Scotland', array['RHS Partner Garden'], 55.5989, -2.7789),
  ('Cae Hir Gardens', 'Ceredigion', 'Wales', array['RHS Partner Garden'], 52.2064, -4.1394),
  ('Dyffryn Fernant Garden', 'Pembrokeshire', 'Wales', array['RHS Partner Garden'], 51.9814, -4.8964),
  ('Plas Cadnant Hidden Gardens', 'Anglesey', 'Wales', array['RHS Partner Garden'], 53.2306, -4.1633)
on conflict (name) do nothing;

-- The Eden Project and Walmer Castle both joined the RHS Partner Garden
-- scheme for 2026, after the original seed was written.
update daysout.properties
set institutions = array_append(institutions, 'RHS Partner Garden')
where name = 'The Eden Project' and not ('RHS Partner Garden' = any(institutions));

update daysout.properties
set institutions = array_append(institutions, 'RHS Partner Garden')
where name = 'Walmer Castle and Gardens' and not ('RHS Partner Garden' = any(institutions));

-- More Historic Houses properties (37 places), reported missing by name
-- (Doddington House, Godinton House) and followed up with a broader regional
-- sweep (Kent, Sussex, Yorkshire, Cotswolds/Midlands, North West, East
-- Anglia, Cornwall/Devon, Scotland, Wales) cross-checked against the existing
-- seed. Gathered from web search result snippets against historichouses.org
-- (which blocks direct fetches), not scraped from an official directory;
-- coordinates are approximate map positions, same caveat as the rest of the
-- seed. Re-running this is safe: existing names are kept.
--
-- No "Doddington House" member could be found under that exact name or in
-- Wiltshire as reported — likely a mix-up with one of these two similarly
-- named members, both included so either (or both) can stay:
-- Doddington Hall and Gardens (Lincolnshire) and Doddington Place Gardens
-- (Kent).

insert into daysout.properties (name, location, country, institutions, latitude, longitude)
values
  ('Godinton House and Gardens', 'Kent', 'England', array['Historic Houses'], 51.1596, 0.8332),
  ('Doddington Hall and Gardens', 'Lincolnshire', 'England', array['Historic Houses'], 53.2196, -0.654),
  ('Doddington Place Gardens', 'Kent', 'England', array['Historic Houses'], 51.2837, 0.7857),
  ('Penshurst Place', 'Kent', 'England', array['Historic Houses'], 51.1746, 0.1838),
  ('Firle Place', 'East Sussex', 'England', array['Historic Houses'], 50.845, 0.0916),
  ('Glynde Place', 'East Sussex', 'England', array['Historic Houses'], 50.8653, 0.0681),
  ('Dorney Court', 'Buckinghamshire', 'England', array['Historic Houses'], 51.5024, -0.6759),
  ('West Dean Gardens', 'West Sussex', 'England', array['Historic Houses'], 50.9052, -0.7814),
  ('Parham House and Gardens', 'West Sussex', 'England', array['Historic Houses'], 50.9177, -0.4933),
  ('Haddon Hall', 'Derbyshire', 'England', array['Historic Houses'], 53.2134, -1.6748),
  ('Arbury Hall', 'Warwickshire', 'England', array['Historic Houses'], 52.5005, -1.5089),
  ('Weston Park', 'Staffordshire', 'England', array['Historic Houses'], 52.6953, -2.3004),
  ('Dalemain', 'Cumbria', 'England', array['Historic Houses'], 54.6343, -2.8115),
  ('Hutton-in-the-Forest', 'Cumbria', 'England', array['Historic Houses'], 54.714, -2.839),
  ('Capesthorne Hall', 'Cheshire', 'England', array['Historic Houses'], 53.2517, -2.2406),
  ('Muncaster Castle', 'Cumbria', 'England', array['Historic Houses'], 54.3546, -3.3808),
  ('Caerhays Castle', 'Cornwall', 'England', array['Historic Houses'], 50.2341, -4.8479),
  ('Kentwell Hall', 'Suffolk', 'England', array['Historic Houses'], 52.0985, 0.7189),
  ('Somerleyton Hall', 'Suffolk', 'England', array['Historic Houses'], 52.5207, 1.6731),
  ('Hindringham Hall', 'Norfolk', 'England', array['Historic Houses'], 52.8907, 0.9401),
  ('Burton Agnes Hall', 'East Yorkshire', 'England', array['Historic Houses'], 54.0529, -0.3139),
  ('Burton Constable Hall', 'East Yorkshire', 'England', array['Historic Houses'], 53.8149, -0.1988),
  ('Bramham Park', 'West Yorkshire', 'England', array['Historic Houses'], 53.8688, -1.3743),
  ('Duncombe Park', 'North Yorkshire', 'England', array['Historic Houses'], 54.2385, -1.0833),
  ('Hovingham Hall', 'North Yorkshire', 'England', array['Historic Houses'], 54.1726, -0.9811),
  ('Ripley Castle', 'North Yorkshire', 'England', array['Historic Houses'], 54.0402, -1.5705),
  ('Markenfield Hall', 'North Yorkshire', 'England', array['Historic Houses'], 54.1016, -1.551),
  ('Norton Conyers', 'North Yorkshire', 'England', array['Historic Houses'], 54.181, -1.5114),
  ('Scampston Hall', 'North Yorkshire', 'England', array['Historic Houses'], 54.1683, -0.677),
  ('Kiplin Hall', 'North Yorkshire', 'England', array['Historic Houses'], 54.372, -1.579),
  ('Plumpton Rocks', 'North Yorkshire', 'England', array['Historic Houses'], 53.9784, -1.4597),
  ('Sion Hill Hall', 'North Yorkshire', 'England', array['Historic Houses'], 54.2541, -1.4283),
  ('Sutton Park', 'North Yorkshire', 'England', array['Historic Houses'], 54.0737, -1.1103),
  ('Bodrhyddan Hall', 'Denbighshire', 'Wales', array['Historic Houses'], 53.2973, -3.4328),
  ('Gwrych Castle', 'Conwy', 'Wales', array['Historic Houses'], 53.2833, -3.6085),
  ('Skaill House', 'Orkney', 'Scotland', array['Historic Houses'], 59.0476, -3.3366),
  ('Dunnottar Castle', 'Aberdeenshire', 'Scotland', array['Historic Houses'], 56.946, -2.1971)
on conflict (name) do nothing;

-- More English Heritage properties (55 places), following up on a report
-- that Hurst Castle was missing, with a broader sweep across London, Kent,
-- Sussex, Hampshire/Isle of Wight, Yorkshire, Northumberland, Cumbria,
-- Cornwall/Devon, East Anglia/Essex, the Midlands, Herefordshire, Somerset
-- and Wiltshire, cross-checked against the existing seed to avoid
-- duplicates. Gathered from web search result snippets against
-- english-heritage.org.uk (which blocks direct fetches) and Wikipedia, not
-- scraped from an official directory; coordinates are approximate map
-- positions, same caveat as the rest of the seed. Re-running this is safe:
-- existing names are kept.
--
-- Three are worth a second look rather than being treated as certain:
-- Conisbrough Castle is jointly associated with Doncaster council rather
-- than solely English Heritage; Leiston Abbey was reported as closed to
-- visitors pending conservation work; Bayham Old Abbey's coordinates came
-- from a lower-confidence source than the others here. All three are kept
-- in since the institution tag and coordinates are already treated as
-- correctable starting points throughout this seed.

insert into daysout.properties (name, location, country, institutions, latitude, longitude)
values
  ('Hurst Castle', 'Hampshire', 'England', array['English Heritage'], 50.7064, -1.5512),
  ('Kenwood House', 'Greater London', 'England', array['English Heritage'], 51.5715, -0.1673),
  ('Marble Hill House', 'Greater London', 'England', array['English Heritage'], 51.4494, -0.3133),
  ('Ranger''s House (The Wernher Collection)', 'Greater London', 'England', array['English Heritage'], 51.4734, -0.0016),
  ('Wellington Arch', 'Greater London', 'England', array['English Heritage'], 51.5025, -0.1508),
  ('Apsley House', 'Greater London', 'England', array['English Heritage'], 51.5035, -0.1517),
  ('Jewel Tower', 'Greater London', 'England', array['English Heritage'], 51.4984, -0.1265),
  ('Deal Castle', 'Kent', 'England', array['English Heritage'], 51.2194, 1.4036),
  ('Reculver Towers and Roman Fort', 'Kent', 'England', array['English Heritage'], 51.3791, 1.2019),
  ('Richborough Roman Fort and Amphitheatre', 'Kent', 'England', array['English Heritage'], 51.294, 1.332),
  ('St Augustine''s Abbey', 'Kent', 'England', array['English Heritage'], 51.2789, 1.0871),
  ('Upnor Castle', 'Kent', 'England', array['English Heritage'], 51.4069, 0.5271),
  ('Bayham Old Abbey', 'Kent', 'England', array['English Heritage'], 51.081, 0.352),
  ('Camber Castle', 'East Sussex', 'England', array['English Heritage'], 50.9331, 0.7325),
  ('Netley Abbey', 'Hampshire', 'England', array['English Heritage'], 50.873, -1.3532),
  ('Calshot Castle', 'Hampshire', 'England', array['English Heritage'], 50.82, -1.3075),
  ('Titchfield Abbey', 'Hampshire', 'England', array['English Heritage'], 50.8571, -1.2322),
  ('Medieval Merchant''s House, Southampton', 'Hampshire', 'England', array['English Heritage'], 50.8985, -1.4052),
  ('Appuldurcombe House', 'Isle of Wight', 'England', array['English Heritage'], 50.6176, -1.2331),
  ('Yarmouth Castle', 'Isle of Wight', 'England', array['English Heritage'], 50.7067, -1.5003),
  ('Middleham Castle', 'North Yorkshire', 'England', array['English Heritage'], 54.2841, -1.8069),
  ('Helmsley Castle', 'North Yorkshire', 'England', array['English Heritage'], 54.2448, -1.0643),
  ('Pickering Castle', 'North Yorkshire', 'England', array['English Heritage'], 54.2483, -0.7748),
  ('Byland Abbey', 'North Yorkshire', 'England', array['English Heritage'], 54.2031, -1.1592),
  ('Mount Grace Priory', 'North Yorkshire', 'England', array['English Heritage'], 54.3801, -1.3111),
  ('Conisbrough Castle', 'South Yorkshire', 'England', array['English Heritage'], 53.4842, -1.2264),
  ('Aydon Castle', 'Northumberland', 'England', array['English Heritage'], 54.9914, -1.9994),
  ('Prudhoe Castle', 'Northumberland', 'England', array['English Heritage'], 54.964, -1.854),
  ('Norham Castle', 'Northumberland', 'England', array['English Heritage'], 55.722, -2.149),
  ('Berwick-upon-Tweed Castle and Ramparts', 'Northumberland', 'England', array['English Heritage'], 55.7742, -2.0119),
  ('Etal Castle', 'Northumberland', 'England', array['English Heritage'], 55.648, -2.121),
  ('Brougham Castle', 'Cumbria', 'England', array['English Heritage'], 54.654, -2.7191),
  ('Pendennis Castle', 'Cornwall', 'England', array['English Heritage'], 50.1472, -5.0478),
  ('St Mawes Castle', 'Cornwall', 'England', array['English Heritage'], 50.1549, -5.0238),
  ('Launceston Castle', 'Cornwall', 'England', array['English Heritage'], 50.6376, -4.3614),
  ('Restormel Castle', 'Cornwall', 'England', array['English Heritage'], 50.4223, -4.6715),
  ('Chysauster Ancient Village', 'Cornwall', 'England', array['English Heritage'], 50.1611, -5.5397),
  ('Okehampton Castle', 'Devon', 'England', array['English Heritage'], 50.7305, -4.0086),
  ('Dartmouth Castle', 'Devon', 'England', array['English Heritage'], 50.342, -3.5683),
  ('Berry Pomeroy Castle', 'Devon', 'England', array['English Heritage'], 50.449, -3.6366),
  ('Totnes Castle', 'Devon', 'England', array['English Heritage'], 50.4321, -3.691),
  ('Castle Acre Castle and Bailey Gate', 'Norfolk', 'England', array['English Heritage'], 52.703, 0.6932),
  ('Binham Priory', 'Norfolk', 'England', array['English Heritage'], 52.9211, 0.9477),
  ('Tilbury Fort', 'Essex', 'England', array['English Heritage'], 51.4528, 0.3747),
  ('Hadleigh Castle', 'Essex', 'England', array['English Heritage'], 51.5444, 0.609),
  ('Leiston Abbey', 'Suffolk', 'England', array['English Heritage'], 52.2214, 1.5776),
  ('Hardwick Old Hall', 'Derbyshire', 'England', array['English Heritage'], 53.1684, -1.3111),
  ('Peveril Castle', 'Derbyshire', 'England', array['English Heritage'], 53.3402, -1.7772),
  ('Wigmore Castle', 'Herefordshire', 'England', array['English Heritage'], 52.3177, -2.8714),
  ('Kirby Muxloe Castle', 'Leicestershire', 'England', array['English Heritage'], 52.6366, -1.2272),
  ('Farleigh Hungerford Castle', 'Somerset', 'England', array['English Heritage'], 51.3167, -2.287),
  ('Cleeve Abbey', 'Somerset', 'England', array['English Heritage'], 51.1556, -3.3642),
  ('Muchelney Abbey', 'Somerset', 'England', array['English Heritage'], 51.0203, -2.8158),
  ('Old Wardour Castle', 'Wiltshire', 'England', array['English Heritage'], 51.0365, -2.0888),
  ('Ludgershall Castle', 'Wiltshire', 'England', array['English Heritage'], 51.2596, -1.6233)
on conflict (name) do nothing;

-- 97 historic parish churches and cathedrals across Kent, East Sussex and
-- West Sussex, sourced from the user's own standalone reference app (not
-- scraped or web-searched, unlike earlier seed batches). New "Historic
-- Church" institution/group, its own progress card and map colour, distinct
-- from the four existing groups. The source data has five metadata fields
-- (built, era, opening hours, note, description) with no matching columns
-- in this schema; rather than add columns for a single new category,
-- built + note + description (and opening hours, where the source had it —
-- only the four cathedrals) are folded into the existing free-text notes
-- column, and era is dropped (the map colours by institution group, not
-- construction date, so it has no display surface here). Checked against
-- the existing seed for name clashes: none found.

insert into daysout.properties (name, location, country, institutions, latitude, longitude, notes)
values
  ('Canterbury Cathedral', 'Kent', 'England', array['Historic Church'], 51.2798, 1.0828, 'Founded 597; rebuilt from 1070s. Mother church of the Church of England; site of Becket''s martyrdom, 1170. England''s primary cathedral since 597 AD, seat of the Archbishop of Canterbury. A UNESCO World Heritage Site rebuilt from Romanesque to Perpendicular Gothic. Opening hours: Mon-Sat 10am-5pm (last entry 4pm); Sun grounds from 11:30am, cathedral from 12:30pm-5pm.'),
  ('Rochester Cathedral', 'Kent', 'England', array['Historic Church'], 51.3886, 0.5024, 'Founded 604; rebuilt from 1080s. England''s second-oldest cathedral, founded 604 AD. A Norman nave with a carved west doorway sits beside later Gothic quire and crypt, on a site used for worship since the 7th century. Opening hours: Mon-Fri 10am-5pm; Sat 10am-4pm; Sun 12pm-4pm.'),
  ('St Augustine''s, Brookland', 'Kent', 'England', array['Historic Church'], 50.9803, 0.7027, '13th century. Detached wooden belfry, leaning at a striking angle. On Romney Marsh, this church keeps its 13th-century octagonal timber bell-tower apart from the main building, shifted by soft marsh ground.'),
  ('St Dunstan''s, Cranbrook', 'Kent', 'England', array['Historic Church'], 51.0956, 0.5461, '14th-15th century. Known as the ''Cathedral of the Weald''. A grand Perpendicular Gothic parish church reflecting Cranbrook''s medieval wealth from the Kent wool and cloth trade.'),
  ('All Saints, Maidstone', 'Kent', 'England', array['Historic Church'], 51.2704, 0.5227, '1395-1420. The largest parish church in Kent, beside the River Medway. Rebuilt in the 14th century by Archbishop Courtenay, standing next to the Archbishop''s Palace on the Medway riverbank.'),
  ('St Mildred''s, Tenterden', 'Kent', 'England', array['Historic Church'], 51.0447, 0.6884, '15th century. Its tower has long guided travellers across the Weald. A spacious church at the heart of a former Cinque Port ''limb'' town, with a prominent 15th-century west tower.'),
  ('St Nicholas, Sevenoaks', 'Kent', 'England', array['Historic Church'], 51.2745, 0.1918, '15th century. Medieval parish church of the market town. A largely 15th-century building with an earlier tower, restored after wartime bomb damage, in the heart of Sevenoaks.'),
  ('St Peter & St Paul, Tonbridge', 'Kent', 'England', array['Historic Church'], 51.1930, 0.2745, '13th century, rebuilt 1877. Ragstone church beside Tonbridge Castle. A substantial parish church of Kentish ragstone, much rebuilt in the 19th century, standing near the Medway and the Norman castle.'),
  ('St Clement''s, Sandwich', 'Kent', 'England', array['Historic Church'], 51.2775, 1.3400, '11th-12th century. Grandest of Sandwich''s three medieval churches. A Norman central tower with striking arcaded decoration survives from this former Cinque Port''s most important church.'),
  ('St Leonard''s, Deal', 'Kent', 'England', array['Historic Church'], 51.2225, 1.4020, '12th century, much rebuilt. Historic parish church of Upper Deal. A part-Norman church with a sturdy tower, serving the older, inland part of Deal before the seafront developed.'),
  ('St Mary the Virgin, Dover', 'Kent', 'England', array['Historic Church'], 51.1279, 1.3117, '12th century, restored 1843. Ancient parish church near Dover''s Roman lighthouse. Standing close to the Roman Pharos and Saxon church within Dover Castle''s grounds, much restored in Victorian times.'),
  ('St Mary & St Eanswythe, Folkestone', 'Kent', 'England', array['Historic Church'], 51.0813, 1.1830, 'Founded 630; present church 13th century. Relics of a Saxon princess-saint found here in 1885. Built on the site of a 7th-century nunnery founded by St Eanswythe, whose rediscovered bones are still kept in the church.'),
  ('St Leonard''s, Hythe', 'Kent', 'England', array['Historic Church'], 51.0700, 1.0800, '13th century. Famous ossuary of ancient bones and skulls in its crypt. A grand church on a hillside above the Cinque Port town, its ambulatory crypt holds one of Britain''s largest bone collections.'),
  ('St Mary the Virgin, Ashford', 'Kent', 'England', array['Historic Church'], 51.1465, 0.8720, '15th century. Perpendicular Gothic church at the market town''s centre. Rebuilt in the 15th century with a prominent central tower, funded by the wealth of Ashford''s wool trade.'),
  ('St Mary of Charity, Faversham', 'Kent', 'England', array['Historic Church'], 51.3167, 0.8930, 'Medieval, spire rebuilt 1755. Unusual openwork crown spire, rare in England. One of Kent''s largest parish churches, rebuilt in the 18th century with a distinctive lantern spire visible across the marshes.'),
  ('All Saints, Whitstable', 'Kent', 'England', array['Historic Church'], 51.3600, 1.0250, '14th century, rebuilt 1876. Parish church of the old oyster-fishing town. A Victorian rebuilding of an older church, close to the harbour that made Whitstable famous for its oysters.'),
  ('St Martin''s, Herne', 'Kent', 'England', array['Historic Church'], 51.3617, 1.1280, '14th century. Medieval flint church of Herne village. A substantial 14th-century church with a tall tower, once the mother church of the neighbouring resort of Herne Bay.'),
  ('St John the Baptist, Margate', 'Kent', 'England', array['Historic Church'], 51.3860, 1.3830, '12th century, rebuilt 19th century. The old parish church predating Margate''s seaside growth. Kent''s largest parish church by area, with Norman origins beneath later medieval and Victorian rebuilding.'),
  ('St George''s, Ramsgate', 'Kent', 'England', array['Historic Church'], 51.3340, 1.4160, '1824-1827. Regency-era ''Cathedral of Thanet''. Built in 1827 with a landmark tower and spire, funded partly by tolls on shipping using Ramsgate''s harbour.'),
  ('St Mary''s, Minster-in-Thanet', 'Kent', 'England', array['Historic Church'], 51.3390, 1.3140, 'Founded 670; present fabric 11th-12th century. One of Britain''s oldest continuously used churches. Founded beside a 7th-century Saxon abbey, its Norman and earlier fabric make it among Kent''s most historic sites.'),
  ('St Mary''s, Wingham', 'Kent', 'England', array['Historic Church'], 51.2670, 1.1980, 'Founded 1286; rebuilt 14th century. Former collegiate church of a medieval community of priests. Founded as a college of priests in 1286, its unusually long chancel reflects that grander original purpose.'),
  ('St Mary''s, Chilham', 'Kent', 'England', array['Historic Church'], 51.2440, 0.9820, '15th century. Overlooks the timber-framed square of a picture-postcard village. A largely 15th-century church facing Chilham Castle across one of Kent''s best-preserved medieval village squares.'),
  ('St Gregory & St Martin, Wye', 'Kent', 'England', array['Historic Church'], 51.1830, 0.9370, 'Medieval, rebuilt 1706. Unusual double dedication in the Stour valley. Rebuilt after a tower collapse in 1686, this college-town church sits below the Wye Crown chalk hill figure.'),
  ('All Saints, Biddenden', 'Kent', 'England', array['Historic Church'], 51.1180, 0.6520, '14th century. Weald church linked to the legendary ''Biddenden Maids''. A 14th-century church at the centre of a timber-framed Wealden village, still tied to an ancient charity legend.'),
  ('St Michael''s, Smarden', 'Kent', 'England', array['Historic Church'], 51.1330, 0.6860, '14th century. Known locally as the ''Barn of Kent'' for its wide roof. A spacious medieval church with an unusually broad nave roof, reflecting Smarden''s cloth-trade prosperity.'),
  ('St Mary''s, Goudhurst', 'Kent', 'England', array['Historic Church'], 51.1120, 0.4530, '13th century, tower 1638. Hilltop church with sweeping Weald views. Sits at the highest point of the village, with fine monuments to the Culpeper family inside.'),
  ('St George''s, Benenden', 'Kent', 'England', array['Historic Church'], 51.0700, 0.6580, 'Medieval, rebuilt after 1830s fire. Weald village church rebuilt after an 1830s fire. A largely 19th-century rebuild on a medieval site, in a quiet Wealden village near Benenden School.'),
  ('All Saints, Lydd', 'Kent', 'England', array['Historic Church'], 50.9520, 0.9110, '13th-15th century. The true ''Cathedral of the Marsh'', tallest tower on Romney Marsh. One of the longest parish churches in England, its soaring tower dominates the flat expanse of Romney Marsh.'),
  ('St Nicholas, New Romney', 'Kent', 'England', array['Historic Church'], 50.9970, 0.9420, '12th century. Norman church left stranded by a shifting shoreline. Once a thriving Cinque Port harbour church, a 13th-century storm silted up the sea and left the town inland.'),
  ('St Thomas Becket, Fairfield', 'Kent', 'England', array['Historic Church'], 51.0080, 0.8720, '13th century (rebuilt 1912). An isolated timber-framed chapel alone in a marsh field. Reached by a footpath across sheep pasture, this weatherboarded church is one of Romney Marsh''s most photographed sights.'),
  ('St Mary''s Abbey, West Malling', 'Kent', 'England', array['Historic Church'], 51.2900, 0.4080, 'Founded c.1090. Still an active Benedictine community. Founded around 1090, the abbey church continues as home to an Anglican Benedictine order of nuns today.'),
  ('St Peter & St Paul, Aylesford', 'Kent', 'England', array['Historic Church'], 51.3050, 0.4880, '13th-14th century. Riverside church in a village of ancient bridges. Overlooks the Medway''s historic multi-arched bridge, near the Carmelite friary known as The Friars.'),
  ('St Nicholas, Leeds', 'Kent', 'England', array['Historic Church'], 51.2500, 0.6300, '12th century. Village church near the moated Leeds Castle. A part-Norman church in the village that lends its name to the famous moated castle nearby.'),
  ('St Mary''s, Chartham', 'Kent', 'England', array['Historic Church'], 51.2530, 1.0080, '13th century. Well-preserved medieval brasses on the Stour. A 13th-century church noted for its collection of monumental brasses, beside the River Stour near Canterbury.'),
  ('Holy Cross, Bearsted', 'Kent', 'England', array['Historic Church'], 51.2670, 0.5850, '13th-14th century. Faces one of Kent''s classic village greens. A medieval flint church overlooking the cricket green at Bearsted, a village little changed in outline for centuries.'),
  ('St Peter & St Paul, Headcorn', 'Kent', 'England', array['Historic Church'], 51.1630, 0.6440, '14th century. One of Kent''s widest timber church roofs. A 14th-century Wealden church with an exceptionally broad nave, funded by the medieval cloth industry.'),
  ('St Bartholomew''s, Otford', 'Kent', 'England', array['Historic Church'], 51.3170, 0.1980, 'Medieval, rebuilt 1853. Near the ruins of a former archbishops'' palace. A Norman-founded church beside the Darent, close to the remains of Otford Palace, once used by Tudor archbishops.'),
  ('St Mary''s, Westerham', 'Kent', 'England', array['Historic Church'], 51.2660, 0.0740, '13th century, restored 19th century. Winston Churchill''s local parish church. A medieval church in the market town where Churchill lived at nearby Chartwell, with memorials to him inside.'),
  ('St Peter & St Paul, Edenbridge', 'Kent', 'England', array['Historic Church'], 51.1980, 0.0670, '13th century. Timber-framed high street church near the Surrey border. A part-13th-century church at the western edge of Kent, in a town that grew around an ancient Eden Bridge crossing.'),
  ('St Mary''s, Lenham', 'Kent', 'England', array['Historic Church'], 51.2160, 0.6980, '13th-14th century. Anchors a well-preserved square below the North Downs. A substantial medieval church facing Lenham''s timber-framed market square at the foot of the chalk downs.'),
  ('St Peter & St Paul, Charing', 'Kent', 'England', array['Historic Church'], 51.2010, 0.7910, 'Medieval, rebuilt after 1590 fire. Former resting place for pilgrims to Canterbury. Sits by the ruins of a palace once used by archbishops, on the old pilgrim road to Canterbury.'),
  ('St Nicholas, Chislehurst', 'Kent', 'England', array['Historic Church'], 51.4160, 0.0680, 'Medieval, rebuilt 1980s after fire. Common-side church at Kent''s historic north-west edge. A rebuilt medieval church facing Chislehurst Common, in what was historically part of Kent before boundary changes.'),
  ('St Peter''s, Ightham', 'Kent', 'England', array['Historic Church'], 51.2890, 0.2350, '13th century. Village church near the moated Ightham Mote. A part-13th-century church in a village famed for its beautifully preserved medieval moated manor house nearby.'),
  ('St Mary Magdalene, Cobham', 'Kent', 'England', array['Historic Church'], 51.3900, 0.4020, '13th-14th century. Renowned collection of medieval memorial brasses. Holds one of England''s finest sets of monumental brasses, alongside almshouses founded by the Cobham family.'),
  ('St Michael''s, Lewes', 'East Sussex', 'England', array['Historic Church'], 50.8724, 0.0116, '12th century. One of only three round-towered churches in Sussex. A flint church on the historic High Street, its unusual round Norman tower a landmark in the county town.'),
  ('St Mary the Virgin, Battle', 'East Sussex', 'England', array['Historic Church'], 50.9155, 0.4835, '12th-13th century. Overlooks the 1066 battlefield and Battle Abbey. A largely 13th-century church with medieval wall paintings, beside the abbey founded on the site of William''s victory.'),
  ('St Thomas the Apostle, Winchelsea', 'East Sussex', 'England', array['Historic Church'], 50.9269, 0.7079, 'Begun 1288. The chancel of a once-cathedral-scale church. Only part of the intended vast church was completed before French raids in the 14th century; fine tomb effigies survive.'),
  ('St Mary''s, Rye', 'East Sussex', 'England', array['Historic Church'], 50.9500, 0.7333, '12th century, much added since. Its turret clock, from 1561, is one of England''s oldest working. A large hilltop church mixing Norman and later work, with wide views over Romney Marsh from the tower.'),
  ('St Mary''s, Eastbourne (Old Town)', 'East Sussex', 'England', array['Historic Church'], 50.7700, 0.2750, '12th century. The original parish church, predating the Victorian resort. A Norman-founded church in Eastbourne''s Old Town, well inland of the seafront that later made the town famous.'),
  ('St Clement''s, Hastings', 'East Sussex', 'England', array['Historic Church'], 50.8560, 0.5730, 'Medieval, rebuilt 1630s. Georgian rebuild in the winding Old Town. Rebuilt after storm damage in the 1630s, this is the parish church of Hastings'' historic Old Town lanes.'),
  ('St Peter''s, Bexhill (Old Town)', 'East Sussex', 'England', array['Historic Church'], 50.8400, 0.4700, 'Saxon origins; Norman additions c.1080s. Ancient parish church of pre-Victorian Bexhill. A Saxon-founded church with Norman additions, in the original village that predates the seaside town by centuries.'),
  ('St Nicolas, Pevensey', 'East Sussex', 'England', array['Historic Church'], 50.8190, 0.3330, '13th century. Within sight of the Roman and Norman fortress. A 13th-century church close to Pevensey Castle, near where William the Conqueror''s fleet landed in 1066.'),
  ('All Saints, Herstmonceux', 'East Sussex', 'England', array['Historic Church'], 50.8850, 0.3320, '13th-14th century. Village church near the moated Tudor castle. A part-medieval church close to Herstmonceux Castle, once home to the Royal Greenwich Observatory.'),
  ('St Andrew''s, Alfriston', 'East Sussex', 'England', array['Historic Church'], 50.8050, 0.1670, '14th century. Called the ''Cathedral of the Downs''. A large 14th-century cruciform church on the village green, beside the Clergy House, the first building acquired by the National Trust.'),
  ('St Michael''s, Berwick', 'East Sussex', 'England', array['Historic Church'], 50.8330, 0.1780, 'Medieval; murals added 1940s. Interior murals by the Bloomsbury Group. Decorated in the 1940s by Vanessa Bell and Duncan Grant, its painted walls are unique among Sussex churches.'),
  ('St Mary & St Peter, Wilmington', 'East Sussex', 'England', array['Historic Church'], 50.8080, 0.1930, '12th century. Beneath the chalk-cut Long Man of Wilmington. A small Norman-founded church with an ancient yew tree, at the foot of the hillside figure it takes its village name from.'),
  ('St Leonard''s, Seaford', 'East Sussex', 'England', array['Historic Church'], 50.7710, 0.1050, '12th century, much rebuilt. Parish church of the old Cinque Port town. A part-Norman church much restored after medieval French raids on this former Channel port.'),
  ('St Mary''s, Ringmer', 'East Sussex', 'England', array['Historic Church'], 50.8880, 0.0870, '13th century. Weald-edge village church near Lewes. A medieval flint church with later brick additions, serving a village long associated with Gideon Mantell''s fossil discoveries nearby.'),
  ('St Dunstan''s, Mayfield', 'East Sussex', 'England', array['Historic Church'], 51.0140, 0.2760, 'Rebuilt after 1389 fire. Linked to the legend of the saint and the Devil''s tongs. Rebuilt after a 14th-century fire, the church stands beside the medieval palace where St Dunstan is said to have worked as a smith.'),
  ('St Peter & St Paul, Wadhurst', 'East Sussex', 'England', array['Historic Church'], 51.0530, 0.3400, '13th century. Cast-iron memorial slabs from the Wealden iron industry. Its floor holds one of the country''s largest collections of iron grave slabs, made in local Wealden furnaces.'),
  ('St Mary''s, Ticehurst', 'East Sussex', 'England', array['Historic Church'], 51.0480, 0.4270, '14th century. High Weald church with a shingled spire. A 14th-century church with later Georgian brick additions, in a High Weald village near the Kent border.'),
  ('St Bartholomew''s, Burwash', 'East Sussex', 'England', array['Historic Church'], 50.9950, 0.4160, '13th century. Rudyard Kipling''s local parish church. Kipling lived nearby at Bateman''s; the church holds an ancient iron grave slab, among the oldest cast in England.'),
  ('St Mary''s, Salehurst', 'East Sussex', 'England', array['Historic Church'], 50.9840, 0.4460, '13th century. Serves Robertsbridge, beside a former Cistercian abbey. A substantial 13th-century church near the ruins of Robertsbridge Abbey, in the Rother valley.'),
  ('St Giles'', Bodiam', 'East Sussex', 'England', array['Historic Church'], 50.9910, 0.5590, '14th century. Neighbours one of England''s most photographed castles. A modest medieval church a short walk from the moated Bodiam Castle, built during the Hundred Years'' War.'),
  ('St Mary''s, Northiam', 'East Sussex', 'England', array['Historic Church'], 50.9880, 0.6280, 'Part-Saxon; mostly 14th-15th century. Queen Elizabeth I is said to have rested under its yew. A part-Saxon church with a famous ancient yew tree on the green, where the queen reputedly changed her shoes in 1573.'),
  ('Holy Cross, Uckfield', 'East Sussex', 'England', array['Historic Church'], 50.9700, 0.0900, 'Rebuilt 1839. Victorian rebuild at the edge of the High Weald. Largely reconstructed in the 19th century, serving the market town where the Weald meets the Sussex Ouse valley.'),
  ('St Denys, Rotherfield', 'East Sussex', 'England', array['Historic Church'], 51.0470, 0.2270, 'Saxon origins; 13th-century fabric. Faint medieval wall paintings survive inside. A Saxon-founded hilltop church with traces of 13th-century murals, overlooking the source of the River Rother.'),
  ('All Saints, Heathfield', 'East Sussex', 'England', array['Historic Church'], 50.9670, 0.2620, '13th century, much rebuilt. High Weald parish church above the old cuckoo fair town. Serves a High Weald market town traditionally said to welcome the first cuckoo of spring at its April fair.'),
  ('St Swithun''s, East Grinstead', 'East Sussex', 'England', array['Historic Church'], 51.1280, -0.0090, 'Rebuilt 1789. Georgian rebuild after a tower collapse. Rebuilt in the 1780s after its medieval predecessor''s tower fell, on Sussex''s border with Surrey and Kent.'),
  ('Chichester Cathedral', 'West Sussex', 'England', array['Historic Church'], 50.8365, -0.7792, '1076-1108. Its spire is visible from the sea; a rare English cathedral spire. Consecrated 1108, with a free-standing medieval bell tower and a modern tapestry behind the high altar. Opening hours: Mon-Sat 9am-5pm; Sun 12:30pm-2:30pm.'),
  ('Arundel Cathedral', 'West Sussex', 'England', array['Historic Church'], 50.8551, -0.5556, '1868-1873. French Gothic-revival, built 1868-1873. A Roman Catholic cathedral commissioned by the Duke of Norfolk, modelled on 13th-century French cathedrals. Opening hours: Mon-Sat 9am-4pm; Sun 12:30pm-4pm.'),
  ('Boxgrove Priory', 'West Sussex', 'England', array['Historic Church'], 50.8577, -0.6797, 'c.1200 (choir). Surviving choir of a Benedictine priory church. Only the 12th-century quire and crossing remain in use as the parish church, amid the wider priory ruins.'),
  ('St Andrew''s, Steyning', 'West Sussex', 'England', array['Historic Church'], 50.8887, -0.3226, '12th century. Among the finest Norman naves in Sussex. Built on the site of a Saxon minster linked to St Cuthman, its round-arched nave is renowned for its carved stonework.'),
  ('Holy Trinity, Bosham', 'West Sussex', 'England', array['Historic Church'], 50.8267, -0.8617, 'Saxon; chancel arch c.1050. Appears in the Bayeux Tapestry; a Saxon chancel arch survives. King Harold is shown praying here before his 1064 voyage; genuine Anglo-Saxon stonework remains in the chancel arch.'),
  ('St Mary''s, Horsham', 'West Sussex', 'England', array['Historic Church'], 51.0625, -0.3272, '13th century. Sussex ''Horsham slab'' stone roof tiles overhead. A 13th-century church roofed in the heavy local sandstone slabs typical of the Horsham area.'),
  ('St Mary''s, Petworth', 'West Sussex', 'England', array['Historic Church'], 50.9970, -0.6106, 'Medieval, rebuilt 1827. Beside the grand parkland of Petworth House. Largely rebuilt in the 19th century, standing at the edge of the National Trust estate and its Capability Brown park.'),
  ('St Mary Magdalene & St Denys, Midhurst', 'West Sussex', 'England', array['Historic Church'], 50.9830, -0.7370, 'Medieval, rebuilt 1880s. Unusual double dedication in a Rother-valley market town. A largely rebuilt Victorian church on a medieval site, near the ruins of Cowdray House.'),
  ('St Mary''s, Pulborough', 'West Sussex', 'England', array['Historic Church'], 50.9560, -0.5170, '12th century. Hilltop church above the Arun water-meadows. A part-Norman church with wide views over the River Arun''s flood plain from its raised churchyard.'),
  ('St Michael''s, Amberley', 'West Sussex', 'England', array['Historic Church'], 50.9080, -0.5460, '12th century. Thatched-cottage village beneath the South Downs. A Norman church with later medieval work, in a village of thatched cottages between the Downs and the Arun wetlands.'),
  ('St Nicholas, Bramber', 'West Sussex', 'England', array['Historic Church'], 50.8890, -0.3000, '12th century. Below the motte of Bramber Castle. What remains is the nave of a larger Norman church built alongside the castle founded soon after 1066.'),
  ('St Mary de Haura, Shoreham-by-Sea', 'West Sussex', 'England', array['Historic Church'], 50.8340, -0.2740, 'c.1103. Name means ''St Mary of the Harbour''. A grand Transitional Norman church, once much larger, reflecting Shoreham''s importance as a medieval port.'),
  ('St Mary''s, Broadwater, Worthing', 'West Sussex', 'England', array['Historic Church'], 50.8210, -0.3760, '12th century. Worthing''s ancient mother church, inland of the seafront. A Norman cruciform church that served as the parish centre long before Worthing grew into a seaside town.'),
  ('St John the Baptist, Findon', 'West Sussex', 'England', array['Historic Church'], 50.8890, -0.4230, '13th century. Downland village church near the sheep fair site. A part-medieval church in a village long known for its historic Findon Sheep Fair on the surrounding Downs.'),
  ('Holy Trinity, Cuckfield', 'West Sussex', 'England', array['Historic Church'], 51.0030, -0.1440, '13th century. Notable medieval roof and wall paintings. A 13th-century church with an elaborately painted wagon roof, at the centre of a well-preserved High Weald village.'),
  ('St Mary Magdalene, Bolney', 'West Sussex', 'England', array['Historic Church'], 50.9840, -0.2140, '13th century. Weald village church of timber and sandstone. A part-13th-century church with a shingled spire, in a scattered Weald parish between Cuckfield and Henfield.'),
  ('St Peter''s, Henfield', 'West Sussex', 'England', array['Historic Church'], 50.9270, -0.2760, '13th century. Overlooks the upper Adur valley. A largely 13th-century church with a later tower, above the water-meadows of the young River Adur.'),
  ('St Mary''s, Sullington', 'West Sussex', 'England', array['Historic Church'], 50.9280, -0.4680, '11th century. Saxon origins, among the oldest churches in Sussex. Retains herringbone Saxon masonry and a Norman font, in a small downland parish near Storrington.'),
  ('St Peter''s, Selsey', 'West Sussex', 'England', array['Historic Church'], 50.7350, -0.7910, 'Medieval; original see lost by 1075. Selsey was the original seat of the South Saxon bishopric. The first Sussex cathedral stood near here before the sea claimed the site and the see moved to Chichester in 1075.'),
  ('St Mary Magdalene, South Bersted', 'West Sussex', 'England', array['Historic Church'], 50.7860, -0.6870, 'Medieval, rebuilt 19th century. The historic parish church serving Bognor Regis. A part-medieval church in the older settlement of South Bersted, which the Georgian resort of Bognor grew up beside.'),
  ('St Mary''s, Climping', 'West Sussex', 'England', array['Historic Church'], 50.8050, -0.5670, '13th century. Unspoiled Norman and Early English work near the coast. Little altered since the 13th century, with a fine carved south doorway, close to the Arun''s mouth at Littlehampton.'),
  ('St Nicholas, Brighton', 'West Sussex', 'England', array['Historic Church'], 50.8250, -0.1500, 'Medieval, rebuilt 1853. The ''Mother Church of Brighton'', on a hill above the town. Medieval in origin, it holds a rare 12th-century black Tournai marble font, predating Brighton''s Regency growth by centuries.'),
  ('St John the Baptist, Sedlescombe', 'East Sussex', 'England', array['Historic Church'], 50.9394, 0.5090, '13th century. A pretty Wealden village on the old road to Hastings. Rebuilt in the early English style in the 13th century on an earlier Norman site, with a south aisle added in 1838.'),
  ('St George, Crowhurst', 'East Sussex', 'England', array['Historic Church'], 50.8779, 0.4644, '12th century; tower 15th century. Recorded here since 772 AD, with a link to King Harold. A 12th-century nave stands beneath a 15th-century tower bearing the Pelham buckle, beside one of Sussex''s largest ancient yew trees.'),
  ('St Laurence, Catsfield', 'East Sussex', 'England', array['Historic Church'], 50.8768, 0.4562, 'Nave c.1100; tower and chancel early 13th century. Recorded in the Domesday Book of 1086. An early Norman nave with a late 12th-century tower, its 13th-century chancel and 19th-century north aisle added around the original core.'),
  ('St Mary the Virgin, Ninfield', 'East Sussex', 'England', array['Historic Church'], 50.8564, 0.4310, '11th-century nave; 13th-century doorway. Stands apart from the village; also recorded in Domesday Book. A modest Norman-founded church with an early 13th-century west doorway, its plain interior shaped mostly by later post-Reformation work.'),
  ('All Saints, Mountfield', 'East Sussex', 'England', array['Historic Church'], 50.9814, 0.5099, 'Nave c.1107-1124; tower c.1180-1200. A little-altered Norman church in the woods west of Battle. Holds the second-largest Norman font in Sussex, with chancel wall paintings ranging from the 12th to the 16th century.'),
  ('St Mary Magdalene, Whatlington', 'East Sussex', 'England', array['Historic Church'], 50.9506, 0.5324, '12th century or earlier; chancel extended 13th century. A remote church in wooded country north-east of Battle. Likely Norman in origin, though only 13th-century and later detail survives visibly today, following restoration in 1862 and a fire in 2012.')
on conflict (name) do nothing;
