-- Day Out tracker: schema, tables and row level security.
-- Run this in the Supabase SQL editor, then add "daysout" to
-- Project Settings > API > Exposed schemas so PostgREST can see it.

create schema if not exists daysout;

create table if not exists daysout.properties (
  id bigint generated by default as identity primary key,
  name text not null unique,
  location text,
  country text not null default 'England'
    check (country in ('England', 'Scotland', 'Wales', 'Northern Ireland')),
  institutions text[] not null default '{}',
  latitude double precision check (latitude between -90 and 90),
  longitude double precision check (longitude between -180 and 180),
  website text,
  notes text,
  created_at timestamptz not null default now()
);

-- A visit is a separate row rather than a flag on the property so a place can be
-- visited more than once, and so "visited but I can't remember when" stays valid
-- (visited_on is nullable).
create table if not exists daysout.visits (
  id bigint generated by default as identity primary key,
  property_id bigint not null references daysout.properties (id) on delete cascade,
  visited_on date,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists visits_property_id_idx on daysout.visits (property_id);
create index if not exists properties_institutions_idx on daysout.properties using gin (institutions);

grant usage on schema daysout to anon, authenticated;
grant all on all tables in schema daysout to anon, authenticated;
grant all on all sequences in schema daysout to anon, authenticated;

alter table daysout.properties enable row level security;
alter table daysout.visits enable row level security;

-- Signed-in users share one household list; the anon key alone cannot read or
-- write, so the published GitHub Pages build is not an open door to the data.
drop policy if exists "authenticated full access to properties" on daysout.properties;
create policy "authenticated full access to properties" on daysout.properties
for all to authenticated
using (true)
with check (true);

drop policy if exists "authenticated full access to visits" on daysout.visits;
create policy "authenticated full access to visits" on daysout.visits
for all to authenticated
using (true)
with check (true);
